### ISSUE TITLE
Z3DMultiCameraCalibration.ini

### ISSUE THREAD

**Issue by StealthGod** [nikolaseu/neuvision#42]
I'm finding this project super interesting and I'd really like to see it running.  I managed to get everything compiling under Windows, but I've hit a roadblock when running the project.

Unless you have an existing .ini file set up, then it doesn't pick any cameras.  I can see that there is some UI in the code for selecting cameras, but it isn't exposed in the main ui.

Do you have a way to set up an .ini or otherwise generate one?  Or perhaps there's a way to easily expose the camera selector ui?

**Comment by StealthGod** [comment]
Working backwards... this is enough to get me rolling.

[Left]
Type=Z3D::ZOpenCVVideoCapturePlugin
DeviceID=0
[Right]
Type=Z3D::ZOpenCVVideoCapturePlugin
DeviceID=1

**Comment by nikolaseu** [comment]
Hi, I'm glad you find it useful. If you want to implement the camera selection like in the other application I'm more than happy to help. Or actually showing the results in the UI instead of saving it in a file without any feedback to the user, or any other missing feature, there's plenty :)
Sadly I just don't have the time to continue developing this anymore, I basically only fix/improve things that I need for other projects

**Comment by StealthGod** [comment]
I got things working to the level I needed. I managed to prove that OpenCV can give an accurate measurement of the offet between two not similar cameras.

**Comment by pomgo** [comment]
How can I contact you？

**Comment by StealthGod** [comment]
Me?  You just did.  Also, email on my profile.
